import { LegalPage } from "@/components/legal/legal-page"
import type { LegalSectionContent } from "@/components/legal/legal-page"
import { useDocumentTitle } from "@/hooks/use-document-title"

const sections: LegalSectionContent[] = [
  { id: "scope", title: "Scope of this policy", paragraphs: ["This Privacy Policy explains how information may be handled when you use the PanelScan website, customer account, ordering and support tools, and the PanelScan mobile application when it becomes available. Features that are not yet connected may display clearly marked preview data rather than real customer information.", "The service may evolve, so the information actually collected depends on the features you choose to use and the integrations that are active at that time."] },
  { id: "information", title: "Information we may collect", paragraphs: ["PanelScan may collect information you provide directly, information created through transactions and service requests, and limited technical information needed to operate and protect the service."], bullets: ["Account details such as name, email address, phone number, role, and account status.", "Contact, delivery, and installation information you submit.", "Order records, selected products, quantities, status, and related customer-service history.", "Installation requests, preferred schedules, site details, and assignment information.", "Messages, support requests, feedback, ratings, and files or images you choose to send.", "Measurement and project information, including room or surface names, dimensions, calculated areas, panel selections, estimates, preview images, and project status.", "Technical information such as browser or app version, device type, diagnostic events, security events, and basic usage information needed to operate the service."] },
  { id: "payments", title: "Payment information", paragraphs: ["Payments may be processed by an external payment provider. The provider may collect and process payment credentials, verification information, and transaction details under its own privacy policy.", "PanelScan may receive limited payment information such as transaction identifiers, amount, status, timestamps, and the payment method category needed to reconcile an order. PanelScan does not claim to store full payment-card numbers or card security codes."] },
  { id: "use", title: "How information is used", paragraphs: ["Information may be used to provide accounts and authenticated features, display products and pricing, process and fulfil orders, coordinate delivery and installation, answer support requests, maintain transaction and project records, and communicate service updates.", "Information may also be used to secure accounts, prevent misuse, diagnose faults, maintain inventory and operational reporting, improve the interface, and comply with lawful obligations."] },
  { id: "measurements", title: "Measurements, estimates, and project results", paragraphs: ["Project information may be used to calculate areas, estimate panel quantities and material cost, organize customer projects, support installation planning, and display saved results across compatible PanelScan experiences.", "Measurement and estimation results should be treated as assistive planning information. If a project is shared with PanelScan staff or an installer for service, relevant measurements, notes, images, and estimates may be available to those authorized participants."] },
  { id: "mobile-ar", title: "Mobile camera, AR, and device capabilities", paragraphs: ["When a PanelScan mobile application and its measurement features become available, the app may request access to camera, motion, depth, or other device capabilities needed to measure surfaces or create visual previews. The permission request and the app's behavior should describe the capability being used at that time.", "This policy does not claim that every camera frame, room image, scan, mesh, or sensor reading is uploaded or retained. Any implemented collection, processing, storage, or deletion behavior should be documented when the mobile feature is released. The PanelScan website does not request camera access for AR measurement."] },
  { id: "sharing", title: "Service providers and sharing", paragraphs: ["PanelScan may share information with service providers only as reasonably needed for their role, such as website and database hosting, communications, diagnostics, storage, payment processing, delivery, and installation coordination.", "Order and delivery information may be shared with delivery providers, while installation and project information may be shared with assigned installers or operational staff. Payment providers process payment information independently under their own terms. PanelScan does not treat preview data as real customer data."] },
  { id: "legal", title: "Legal requirements and protection", paragraphs: ["Information may be preserved or disclosed where required by applicable law, a valid legal process, or a lawful request, or where reasonably necessary to protect customers, staff, the public, the service, or legal rights.", "PanelScan may also use relevant records to investigate fraud, security incidents, abuse, payment disputes, or violations of service terms."] },
  { id: "security", title: "Security", paragraphs: ["PanelScan uses technical and organizational safeguards appropriate to the service, such as authenticated access, role-based backend authorization, protected hosting configuration, and limited access to operational data. No online service or storage method can guarantee absolute security.", "Keep your account credentials confidential, use a unique password, and contact PanelScan if you suspect unauthorized access. Do not send passwords, full card information, or private access tokens through ordinary support messages."] },
  { id: "retention", title: "Retention", paragraphs: ["Information is retained for as long as reasonably necessary for the purposes described here, including account operation, fulfilment, customer support, project continuity, security, record keeping, dispute handling, and legal obligations.", "Retention can vary by category and context. This policy does not invent a fixed period. Information may be deleted, anonymized, or retained longer where required or permitted for legitimate and lawful reasons."] },
  { id: "rights", title: "Your choices and rights", paragraphs: ["Depending on applicable law and the circumstances, you may have rights to request access to, correction of, or deletion of certain personal information, to object to or restrict certain uses, or to receive information about processing.", "Requests may require identity verification and may be limited where records must be kept for transactions, security, legal obligations, or the rights of others. You can also update some account details through available account features or contact support."] },
  { id: "cookies", title: "Cookies and local storage", paragraphs: ["The website may use cookies, browser storage, or similar technologies for essential session functions, security, preferences, cart or account continuity, and service operation. The current web application may also keep authentication tokens in browser storage after a successful backend login.", "Optional analytics or additional tracking should be described and offered with appropriate controls when enabled. You can use browser settings to manage storage, but blocking essential storage may prevent account or checkout features from working."] },
  { id: "children-transfers", title: "Special contexts and data location", paragraphs: ["PanelScan is intended for customers able to enter into the relevant purchase or service arrangements. If information relating to another person is submitted for delivery, installation, or a shared project, you should have authority to provide it.", "Hosting and service providers may process information in locations different from yours. Appropriate safeguards should be used where required, but this policy does not claim a specific hosting location or cross-border compliance framework that has not been confirmed."] },
  { id: "changes-contact", title: "Policy changes and contact", paragraphs: ["PanelScan may update this policy as website, backend, payment, delivery, installation, mobile AR, 3D, and measurement features develop. The updated page will show a revised date, and material changes may be communicated through an appropriate service channel.", "For privacy questions or requests, use the support or messaging channel made available through PanelScan or the business contact information provided with your order or service interaction. No Data Protection Officer or specific legal entity contact is named here because those details have not been provided."] },
]

export function PrivacyPage() {
  useDocumentTitle("Privacy Policy | PanelScan")
  return <LegalPage eyebrow="Privacy" title="Privacy Policy" introduction="How PanelScan may handle account, commerce, support, installation, and mobile-generated project information as the service develops." sections={sections} />
}
