import { LegalPage } from "@/components/legal/legal-page"
import type { LegalSectionContent } from "@/components/legal/legal-page"
import { useDocumentTitle } from "@/hooks/use-document-title"

const sections: LegalSectionContent[] = [
  { id: "acceptance", title: "Acceptance of these terms", paragraphs: ["These Terms of Service govern access to and use of the PanelScan website, customer portal, related mobile experiences when available, product ordering tools, measurement and estimation features, and services coordinated through PanelScan. By using the service, creating an account, or placing an order, you agree to these terms.", "If you do not agree, do not use the service. Additional terms shown for a particular order, payment provider, delivery, installation, or mobile feature may also apply where they are presented before use."] },
  { id: "accounts", title: "Account responsibilities", paragraphs: ["You are responsible for providing accurate account and contact information, maintaining the confidentiality of your sign-in details, and notifying PanelScan if you believe your account has been accessed without permission.", "You may not share staff or administrative access, impersonate another person, or use another customer's project, order, or measurement records without authorization. PanelScan may restrict access where reasonably necessary to protect customers, the service, or business operations."] },
  { id: "products-pricing", title: "Products and pricing", paragraphs: ["Product descriptions, dimensions, finishes, availability, and prices are presented for customer planning and ordering. Prices may change before an order is placed, and pricing visible in a customer account does not guarantee future availability or price.", "Taxes, delivery, installation, accessories, trims, preparation work, and other charges may be shown separately where applicable. A displayed estimate is not a final quotation unless PanelScan expressly confirms it as such."] },
  { id: "orders", title: "Orders", paragraphs: ["An order is a request to purchase the listed products. PanelScan may review product availability, quantities, delivery details, and other order information before fulfilment. An automated acknowledgement does not necessarily mean every item has been accepted or reserved.", "PanelScan may contact you to clarify an order or may decline or adjust an order when an item is unavailable, information is incomplete, pricing is clearly erroneous, or fulfilment is not reasonably possible. Any resulting payment handling will follow the applicable payment-provider and customer-service process."] },
  { id: "payment", title: "Payment", paragraphs: ["Payments may be processed through an external payment provider. That provider may apply its own terms, privacy practices, verification steps, and transaction limits. PanelScan does not ask you to provide full payment-card details through ordinary support messages.", "An order may remain pending until the payment provider and PanelScan confirm the relevant transaction status. Do not close or repeat a payment solely because a status update is delayed; contact support if the result is unclear."] },
  { id: "delivery", title: "Delivery", paragraphs: ["Delivery availability, timing, fees, and hand-off arrangements depend on the order, destination, product handling needs, and delivery provider. Any date or time shown before final confirmation is an estimate and may be affected by stock, transport, access, weather, or other circumstances.", "You are responsible for providing an accurate delivery location and a suitable person or process to receive the goods. Inspect deliveries promptly and report visible issues through the available support channel with appropriate order information."] },
  { id: "installation", title: "Installation services", paragraphs: ["Installation may be arranged separately from product purchase and remains subject to scheduling, site access, surface condition, safety, installer availability, and confirmation by the PanelScan or Disenyo Interior Solution team.", "Customers should disclose relevant site conditions and ensure safe, lawful access. Additional preparation, repairs, electrical work, structural work, removal, or specialist services are not included unless explicitly confirmed. Installation timing and price should be verified before work begins."] },
  { id: "measurements", title: "Measurements and estimates", paragraphs: ["Dimensions, area calculations, panel quantities, material costs, reports, and other estimates are assistive planning outputs. They may depend on values entered by a user, product coverage data, waste allowances, room geometry, obstructions, and assumptions that require site verification.", "Measurements and estimates must be checked before ordering final quantities, cutting material, committing to installation, or relying on a budget. PanelScan may update estimation logic or product coverage information as the service develops."] },
  { id: "mobile-ar", title: "AR, 3D, and mobile measurement disclaimer", paragraphs: ["AR and 3D measurement features, when available, are intended for the PanelScan mobile application. The website may display project results saved by the mobile app but does not represent that AR measurement runs in the browser.", "AR and 3D results may vary because of device capability, camera and sensor quality, environment, lighting, calibration, user movement and input, surface detection, image quality, obstructions, and other technical factors. Visual previews are illustrative and may not reproduce exact scale, alignment, colour, texture, lighting, or installed appearance.", "Always independently verify measurements and estimates before final installation or material cutting. A mobile-generated result does not replace professional site assessment where one is appropriate."] },
  { id: "imagery", title: "Product imagery and finish variation", paragraphs: ["Product images, room scenes, thumbnails, and 3D previews may be representative. Screen settings, photography, lighting, production batches, surface texture, and surrounding materials can affect perceived colour and finish.", "Where colour, grain, profile, or pattern matching is important, confirm the current product specification and, where available, review an appropriate physical sample before ordering or installation."] },
  { id: "stock", title: "Availability and stock", paragraphs: ["Stock indicators are operational information and may change as orders, returns, adjustments, or supplier deliveries are processed. An item shown as available is not necessarily reserved until the applicable order process is complete.", "PanelScan may substitute nothing without your agreement. If an item becomes unavailable, the team may discuss alternatives, revised timing, order adjustment, or cancellation of the affected item."] },
  { id: "cancellations", title: "Cancellations and refunds", paragraphs: ["Cancellation, return, replacement, and refund options depend on the product, order status, condition, customization, applicable customer rights, payment status, and any policy communicated for the transaction. Contact PanelScan promptly if you need to change or cancel an order.", "Do not assume a specific cancellation window, return period, warranty, or refund entitlement unless it has been provided for your order or is required by applicable law. Nothing in these terms limits mandatory consumer rights that cannot lawfully be excluded."] },
  { id: "intellectual-property", title: "Intellectual property", paragraphs: ["The PanelScan service, branding, interface, original text, graphics, software, estimation presentation, and related materials are owned by or licensed to the relevant PanelScan service operator, except for third-party materials identified as such.", "You may use the service for legitimate personal or business purchasing and project-planning purposes. You may not copy, resell, reverse engineer, scrape, or commercially exploit protected service content except where permitted by law or written authorization."] },
  { id: "prohibited-use", title: "Prohibited use", paragraphs: ["You must not misuse PanelScan, interfere with its security or availability, probe protected systems, submit malicious code, automate abusive traffic, upload unlawful content, misrepresent measurements or identity, infringe others' rights, or use the service for fraudulent or unlawful activity.", "You must not use demo or preview interfaces as evidence of a real transaction, approval, inventory record, customer record, or administrative decision."] },
  { id: "third-parties", title: "Third-party services", paragraphs: ["PanelScan may rely on payment processors, hosting providers, communications services, delivery providers, installers, mapping or storage services, and mobile-platform capabilities. Third-party services may be governed by their own terms and privacy practices.", "Links or integrations do not guarantee a third party's continuous availability. PanelScan is responsible for its own service obligations but does not control independent third-party systems."] },
  { id: "liability", title: "Service availability and limitation of liability", paragraphs: ["PanelScan is provided on an as-available basis. The service may occasionally be interrupted for maintenance, changes, provider outages, security work, or circumstances beyond reasonable control. Preview and fallback data are not live business records.", "To the extent permitted by applicable law, PanelScan is not responsible for indirect or consequential loss arising solely from reliance on unverified measurements, estimates, visual previews, availability indicators, or third-party services. This section does not exclude liability or rights that cannot lawfully be excluded."] },
  { id: "changes-contact", title: "Changes, applicable law, and contact", paragraphs: ["PanelScan may update these terms as products, mobile features, legal requirements, or operating practices change. The updated version will show a revised date, and material changes may be communicated through an appropriate service channel.", "These terms are subject to applicable law and mandatory consumer protections. Any governing law or dispute forum not specifically communicated for a transaction will be determined under applicable legal rules rather than invented here.", "For questions about these terms, an order, delivery, installation, or measurement result, use the support or messaging channel made available on the PanelScan website or the business contact information provided with your transaction."] },
]

export function TermsPage() {
  useDocumentTitle("Terms of Service | PanelScan")
  return <LegalPage eyebrow="Legal" title="Terms of Service" introduction="Terms for using PanelScan's storefront, customer portal, ordering, installation coordination, and current or future mobile measurement tools." sections={sections} />
}
